/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserUsageDto } from './UserUsageDto';
import {
    UserUsageDtoFromJSON,
    UserUsageDtoFromJSONTyped,
    UserUsageDtoToJSON,
    UserUsageDtoToJSONTyped,
} from './UserUsageDto';

/**
 * 사용자별 사용량 조회 응답
 * @export
 * @interface AdminUserUsageResponse
 */
export interface AdminUserUsageResponse {
    /**
     * 사용자별 사용량 목록
     * @type {Array<UserUsageDto>}
     * @memberof AdminUserUsageResponse
     */
    users: Array<UserUsageDto>;
}

/**
 * Check if a given object implements the AdminUserUsageResponse interface.
 */
export function instanceOfAdminUserUsageResponse(value: object): value is AdminUserUsageResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function AdminUserUsageResponseFromJSON(json: any): AdminUserUsageResponse {
    return AdminUserUsageResponseFromJSONTyped(json, false);
}

export function AdminUserUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserUsageDtoFromJSON)),
    };
}

export function AdminUserUsageResponseToJSON(json: any): AdminUserUsageResponse {
    return AdminUserUsageResponseToJSONTyped(json, false);
}

export function AdminUserUsageResponseToJSONTyped(value?: AdminUserUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(UserUsageDtoToJSON)),
    };
}

