/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendedQuestionUserScoreDto } from './RecommendedQuestionUserScoreDto';
import {
    RecommendedQuestionUserScoreDtoFromJSON,
    RecommendedQuestionUserScoreDtoFromJSONTyped,
    RecommendedQuestionUserScoreDtoToJSON,
    RecommendedQuestionUserScoreDtoToJSONTyped,
} from './RecommendedQuestionUserScoreDto';

/**
 * 일기 정보
 * @export
 * @interface AdminDiaryDto
 */
export interface AdminDiaryDto {
    /**
     * 일기 ID
     * @type {string}
     * @memberof AdminDiaryDto
     */
    diaryId: string;
    /**
     * 작성자 ID
     * @type {string}
     * @memberof AdminDiaryDto
     */
    uploaderId: string;
    /**
     * 일기 작성 날짜
     * @type {Date}
     * @memberof AdminDiaryDto
     */
    date: Date;
    /**
     * 일기 내용
     * @type {string}
     * @memberof AdminDiaryDto
     */
    content: string;
    /**
     * 감정 상태
     * @type {string}
     * @memberof AdminDiaryDto
     */
    emotion: AdminDiaryDtoEmotionEnum;
    /**
     * 생성 일시
     * @type {Date}
     * @memberof AdminDiaryDto
     */
    createdAt: Date;
    /**
     * 추천 질문에 대한 사용자 점수 목록
     * @type {Array<RecommendedQuestionUserScoreDto>}
     * @memberof AdminDiaryDto
     */
    questionScores: Array<RecommendedQuestionUserScoreDto>;
}


/**
 * @export
 */
export const AdminDiaryDtoEmotionEnum = {
    Happy: 'HAPPY',
    Love: 'LOVE',
    Sad: 'SAD'
} as const;
export type AdminDiaryDtoEmotionEnum = typeof AdminDiaryDtoEmotionEnum[keyof typeof AdminDiaryDtoEmotionEnum];


/**
 * Check if a given object implements the AdminDiaryDto interface.
 */
export function instanceOfAdminDiaryDto(value: object): value is AdminDiaryDto {
    if (!('diaryId' in value) || value['diaryId'] === undefined) return false;
    if (!('uploaderId' in value) || value['uploaderId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('questionScores' in value) || value['questionScores'] === undefined) return false;
    return true;
}

export function AdminDiaryDtoFromJSON(json: any): AdminDiaryDto {
    return AdminDiaryDtoFromJSONTyped(json, false);
}

export function AdminDiaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDiaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'diaryId': json['diaryId'],
        'uploaderId': json['uploaderId'],
        'date': (new Date(json['date'])),
        'content': json['content'],
        'emotion': json['emotion'],
        'createdAt': (new Date(json['createdAt'])),
        'questionScores': ((json['questionScores'] as Array<any>).map(RecommendedQuestionUserScoreDtoFromJSON)),
    };
}

export function AdminDiaryDtoToJSON(json: any): AdminDiaryDto {
    return AdminDiaryDtoToJSONTyped(json, false);
}

export function AdminDiaryDtoToJSONTyped(value?: AdminDiaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaryId': value['diaryId'],
        'uploaderId': value['uploaderId'],
        'date': value['date'].toISOString().substring(0,10),
        'content': value['content'],
        'emotion': value['emotion'],
        'createdAt': value['createdAt'].toISOString(),
        'questionScores': ((value['questionScores'] as Array<any>).map(RecommendedQuestionUserScoreDtoToJSON)),
    };
}

