/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDiaryDto } from './AdminDiaryDto';
import {
    AdminDiaryDtoFromJSON,
    AdminDiaryDtoFromJSONTyped,
    AdminDiaryDtoToJSON,
    AdminDiaryDtoToJSONTyped,
} from './AdminDiaryDto';

/**
 * 관리자 일기 목록 조회 응답
 * @export
 * @interface AdminDiaryFindAllResponse
 */
export interface AdminDiaryFindAllResponse {
    /**
     * 일기 목록
     * @type {Array<AdminDiaryDto>}
     * @memberof AdminDiaryFindAllResponse
     */
    diaries: Array<AdminDiaryDto>;
}

/**
 * Check if a given object implements the AdminDiaryFindAllResponse interface.
 */
export function instanceOfAdminDiaryFindAllResponse(value: object): value is AdminDiaryFindAllResponse {
    if (!('diaries' in value) || value['diaries'] === undefined) return false;
    return true;
}

export function AdminDiaryFindAllResponseFromJSON(json: any): AdminDiaryFindAllResponse {
    return AdminDiaryFindAllResponseFromJSONTyped(json, false);
}

export function AdminDiaryFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDiaryFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diaries': ((json['diaries'] as Array<any>).map(AdminDiaryDtoFromJSON)),
    };
}

export function AdminDiaryFindAllResponseToJSON(json: any): AdminDiaryFindAllResponse {
    return AdminDiaryFindAllResponseToJSONTyped(json, false);
}

export function AdminDiaryFindAllResponseToJSONTyped(value?: AdminDiaryFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaries': ((value['diaries'] as Array<any>).map(AdminDiaryDtoToJSON)),
    };
}

