/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageDetail } from './UsageDetail';
import {
    UsageDetailFromJSON,
    UsageDetailFromJSONTyped,
    UsageDetailToJSON,
    UsageDetailToJSONTyped,
} from './UsageDetail';

/**
 * 관리자 사용량 조회 응답
 * @export
 * @interface AdminUsageResponse
 */
export interface AdminUsageResponse {
    /**
     * 누적 사용량
     * @type {UsageDetail}
     * @memberof AdminUsageResponse
     */
    cumulative: UsageDetail;
    /**
     * 월간 사용량
     * @type {UsageDetail}
     * @memberof AdminUsageResponse
     */
    monthly: UsageDetail;
}

/**
 * Check if a given object implements the AdminUsageResponse interface.
 */
export function instanceOfAdminUsageResponse(value: object): value is AdminUsageResponse {
    if (!('cumulative' in value) || value['cumulative'] === undefined) return false;
    if (!('monthly' in value) || value['monthly'] === undefined) return false;
    return true;
}

export function AdminUsageResponseFromJSON(json: any): AdminUsageResponse {
    return AdminUsageResponseFromJSONTyped(json, false);
}

export function AdminUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cumulative': UsageDetailFromJSON(json['cumulative']),
        'monthly': UsageDetailFromJSON(json['monthly']),
    };
}

export function AdminUsageResponseToJSON(json: any): AdminUsageResponse {
    return AdminUsageResponseToJSONTyped(json, false);
}

export function AdminUsageResponseToJSONTyped(value?: AdminUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cumulative': UsageDetailToJSON(value['cumulative']),
        'monthly': UsageDetailToJSON(value['monthly']),
    };
}

