/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * 관리자 사용자 정보
 * @export
 * @interface AdminUserDto
 */
export interface AdminUserDto {
  /**
   * 사용자 ID
   * @type {string}
   * @memberof AdminUserDto
   */
  userId: string;
  /**
   * 이름
   * @type {string}
   * @memberof AdminUserDto
   */
  name: string;
  /**
   * 생년월일
   * @type {Date}
   * @memberof AdminUserDto
   */
  birthDate: Date;
  /**
   * 주 진단명
   * @type {string}
   * @memberof AdminUserDto
   */
  primaryDiagnosis?: string;
  /**
   * 위험군 여부
   * @type {boolean}
   * @memberof AdminUserDto
   */
  atRisk: boolean;
}

/**
 * Check if a given object implements the AdminUserDto interface.
 */
export function instanceOfAdminUserDto(value: object): value is AdminUserDto {
  if (!("userId" in value) || value["userId"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("birthDate" in value) || value["birthDate"] === undefined) return false;
  if (!("atRisk" in value) || value["atRisk"] === undefined) return false;
  return true;
}

export function AdminUserDtoFromJSON(json: any): AdminUserDto {
  return AdminUserDtoFromJSONTyped(json, false);
}

export function AdminUserDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminUserDto {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"],
    name: json["name"],
    birthDate: new Date(json["birthDate"]),
    primaryDiagnosis:
      json["primaryDiagnosis"] == null ? undefined : json["primaryDiagnosis"],
    atRisk: json["atRisk"],
  };
}

export function AdminUserDtoToJSON(json: any): AdminUserDto {
  return AdminUserDtoToJSONTyped(json, false);
}

export function AdminUserDtoToJSONTyped(
  value?: AdminUserDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    name: value["name"],
    birthDate: value["birthDate"].toISOString().substring(0, 10),
    primaryDiagnosis: value["primaryDiagnosis"],
    atRisk: value["atRisk"],
  };
}
