/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUsageResponse } from './AdminUsageResponse';
import {
    AdminUsageResponseFromJSON,
    AdminUsageResponseFromJSONTyped,
    AdminUsageResponseToJSON,
    AdminUsageResponseToJSONTyped,
} from './AdminUsageResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUsageResponse
 */
export interface CommonResponseAdminUsageResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUsageResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUsageResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUsageResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUsageResponse}
     * @memberof CommonResponseAdminUsageResponse
     */
    data?: AdminUsageResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUsageResponse interface.
 */
export function instanceOfCommonResponseAdminUsageResponse(value: object): value is CommonResponseAdminUsageResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUsageResponseFromJSON(json: any): CommonResponseAdminUsageResponse {
    return CommonResponseAdminUsageResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUsageResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUsageResponseToJSON(json: any): CommonResponseAdminUsageResponse {
    return CommonResponseAdminUsageResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUsageResponseToJSONTyped(value?: CommonResponseAdminUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUsageResponseToJSON(value['data']),
    };
}

