/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserUsageResponse } from './AdminUserUsageResponse';
import {
    AdminUserUsageResponseFromJSON,
    AdminUserUsageResponseFromJSONTyped,
    AdminUserUsageResponseToJSON,
    AdminUserUsageResponseToJSONTyped,
} from './AdminUserUsageResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserUsageResponse
 */
export interface CommonResponseAdminUserUsageResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserUsageResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserUsageResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserUsageResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserUsageResponse}
     * @memberof CommonResponseAdminUserUsageResponse
     */
    data?: AdminUserUsageResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserUsageResponse interface.
 */
export function instanceOfCommonResponseAdminUserUsageResponse(value: object): value is CommonResponseAdminUserUsageResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserUsageResponseFromJSON(json: any): CommonResponseAdminUserUsageResponse {
    return CommonResponseAdminUserUsageResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserUsageResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserUsageResponseToJSON(json: any): CommonResponseAdminUserUsageResponse {
    return CommonResponseAdminUserUsageResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserUsageResponseToJSONTyped(value?: CommonResponseAdminUserUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserUsageResponseToJSON(value['data']),
    };
}

