/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDiaryFindAllResponse } from './AdminDiaryFindAllResponse';
import {
    AdminDiaryFindAllResponseFromJSON,
    AdminDiaryFindAllResponseFromJSONTyped,
    AdminDiaryFindAllResponseToJSON,
    AdminDiaryFindAllResponseToJSONTyped,
} from './AdminDiaryFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminDiaryFindAllResponse
 */
export interface CommonResponseAdminDiaryFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminDiaryFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {AdminDiaryFindAllResponse}
     * @memberof CommonResponseAdminDiaryFindAllResponse
     */
    data?: AdminDiaryFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminDiaryFindAllResponse interface.
 */
export function instanceOfCommonResponseAdminDiaryFindAllResponse(value: object): value is CommonResponseAdminDiaryFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminDiaryFindAllResponseFromJSON(json: any): CommonResponseAdminDiaryFindAllResponse {
    return CommonResponseAdminDiaryFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminDiaryFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminDiaryFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminDiaryFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminDiaryFindAllResponseToJSON(json: any): CommonResponseAdminDiaryFindAllResponse {
    return CommonResponseAdminDiaryFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseAdminDiaryFindAllResponseToJSONTyped(value?: CommonResponseAdminDiaryFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminDiaryFindAllResponseToJSON(value['data']),
    };
}

