/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 사용량 상세
 * @export
 * @interface UsageDetail
 */
export interface UsageDetail {
    /**
     * 사용자 수
     * @type {number}
     * @memberof UsageDetail
     */
    userCount: number;
    /**
     * 분석 건 수
     * @type {number}
     * @memberof UsageDetail
     */
    analysisCount: number;
    /**
     * 사용료 (원)
     * @type {number}
     * @memberof UsageDetail
     */
    usageFee: number;
}

/**
 * Check if a given object implements the UsageDetail interface.
 */
export function instanceOfUsageDetail(value: object): value is UsageDetail {
    if (!('userCount' in value) || value['userCount'] === undefined) return false;
    if (!('analysisCount' in value) || value['analysisCount'] === undefined) return false;
    if (!('usageFee' in value) || value['usageFee'] === undefined) return false;
    return true;
}

export function UsageDetailFromJSON(json: any): UsageDetail {
    return UsageDetailFromJSONTyped(json, false);
}

export function UsageDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'userCount': json['userCount'],
        'analysisCount': json['analysisCount'],
        'usageFee': json['usageFee'],
    };
}

export function UsageDetailToJSON(json: any): UsageDetail {
    return UsageDetailToJSONTyped(json, false);
}

export function UsageDetailToJSONTyped(value?: UsageDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userCount': value['userCount'],
        'analysisCount': value['analysisCount'],
        'usageFee': value['usageFee'],
    };
}

