/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 사용자별 사용량
 * @export
 * @interface UserUsageDto
 */
export interface UserUsageDto {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof UserUsageDto
     */
    userId: string;
    /**
     * 사용자 이름
     * @type {string}
     * @memberof UserUsageDto
     */
    userName?: string;
    /**
     * 일기 작성 건수
     * @type {number}
     * @memberof UserUsageDto
     */
    diaryCount: number;
    /**
     * 분석 건수
     * @type {number}
     * @memberof UserUsageDto
     */
    analysisCount: number;
}

/**
 * Check if a given object implements the UserUsageDto interface.
 */
export function instanceOfUserUsageDto(value: object): value is UserUsageDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('diaryCount' in value) || value['diaryCount'] === undefined) return false;
    if (!('analysisCount' in value) || value['analysisCount'] === undefined) return false;
    return true;
}

export function UserUsageDtoFromJSON(json: any): UserUsageDto {
    return UserUsageDtoFromJSONTyped(json, false);
}

export function UserUsageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUsageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'diaryCount': json['diaryCount'],
        'analysisCount': json['analysisCount'],
    };
}

export function UserUsageDtoToJSON(json: any): UserUsageDto {
    return UserUsageDtoToJSONTyped(json, false);
}

export function UserUsageDtoToJSONTyped(value?: UserUsageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'diaryCount': value['diaryCount'],
        'analysisCount': value['analysisCount'],
    };
}

