/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseAdminUsageResponse,
  CommonResponseAdminUserUsageResponse,
} from '../models/index';
import {
    CommonResponseAdminUsageResponseFromJSON,
    CommonResponseAdminUsageResponseToJSON,
    CommonResponseAdminUserUsageResponseFromJSON,
    CommonResponseAdminUserUsageResponseToJSON,
} from '../models/index';

export interface GetUserUsagesRequest {
    search?: string;
}

/**
 * 
 */
export class AdminUsageApi extends runtime.BaseAPI {

    /**
     * 누적 사용량과 월간 사용량을 조회합니다. 사용자 수, 분석 건 수, 사용료를 포함합니다.
     * 사용량 조회
     */
    async getUsageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUsageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/usage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUsageResponseFromJSON(jsonValue));
    }

    /**
     * 누적 사용량과 월간 사용량을 조회합니다. 사용자 수, 분석 건 수, 사용료를 포함합니다.
     * 사용량 조회
     */
    async getUsage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUsageResponse> {
        const response = await this.getUsageRaw(initOverrides);
        return await response.value();
    }

    /**
     * 사용자별 일기 작성 건수와 분석 건수를 조회합니다. 사용자 이름으로 검색할 수 있습니다.
     * 사용자별 사용량 조회
     */
    async getUserUsagesRaw(requestParameters: GetUserUsagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUserUsageResponse>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/usage/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUserUsageResponseFromJSON(jsonValue));
    }

    /**
     * 사용자별 일기 작성 건수와 분석 건수를 조회합니다. 사용자 이름으로 검색할 수 있습니다.
     * 사용자별 사용량 조회
     */
    async getUserUsages(requestParameters: GetUserUsagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUserUsageResponse> {
        const response = await this.getUserUsagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
