/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseAdminDiaryFindAllResponse,
  CommonResponseAdminDiaryKeywordResponse,
  CommonResponseAdminDiarySdohResponse,
  CommonResponseAdminDiaryWelfareServiceResponse,
} from '../models/index';
import {
    CommonResponseAdminDiaryFindAllResponseFromJSON,
    CommonResponseAdminDiaryFindAllResponseToJSON,
    CommonResponseAdminDiaryKeywordResponseFromJSON,
    CommonResponseAdminDiaryKeywordResponseToJSON,
    CommonResponseAdminDiarySdohResponseFromJSON,
    CommonResponseAdminDiarySdohResponseToJSON,
    CommonResponseAdminDiaryWelfareServiceResponseFromJSON,
    CommonResponseAdminDiaryWelfareServiceResponseToJSON,
} from '../models/index';

export interface FindAllByUserIdAndDateRequest {
    userId: string;
    date: Date;
}

export interface FindExtractedKeywordsRequest {
    diaryId: string;
}

export interface FindSdohRequest {
    diaryId: string;
}

export interface FindWelfareServicesRequest {
    diaryId: string;
}

/**
 * 
 */
export class AdminDiaryApi extends runtime.BaseAPI {

    /**
     * 특정 사용자가 특정 날짜에 작성한 일기 목록을 조회합니다.
     * 사용자별 일기 목록 조회
     */
    async findAllByUserIdAndDateRaw(requestParameters: FindAllByUserIdAndDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminDiaryFindAllResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling findAllByUserIdAndDate().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling findAllByUserIdAndDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/diaries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminDiaryFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 특정 사용자가 특정 날짜에 작성한 일기 목록을 조회합니다.
     * 사용자별 일기 목록 조회
     */
    async findAllByUserIdAndDate(requestParameters: FindAllByUserIdAndDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminDiaryFindAllResponse> {
        const response = await this.findAllByUserIdAndDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 일기에서 추출된 키워드 정보를 조회합니다.
     * 일기 추출 키워드 조회
     */
    async findExtractedKeywordsRaw(requestParameters: FindExtractedKeywordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminDiaryKeywordResponse>> {
        if (requestParameters['diaryId'] == null) {
            throw new runtime.RequiredError(
                'diaryId',
                'Required parameter "diaryId" was null or undefined when calling findExtractedKeywords().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/diaries/{diaryId}/keywords`;
        urlPath = urlPath.replace(`{${"diaryId"}}`, encodeURIComponent(String(requestParameters['diaryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminDiaryKeywordResponseFromJSON(jsonValue));
    }

    /**
     * 특정 일기에서 추출된 키워드 정보를 조회합니다.
     * 일기 추출 키워드 조회
     */
    async findExtractedKeywords(requestParameters: FindExtractedKeywordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminDiaryKeywordResponse> {
        const response = await this.findExtractedKeywordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 일기의 사회적 건강 결정요인(Social Determinants of Health) 정보를 조회합니다.
     * 일기 SDoH 조회
     */
    async findSdohRaw(requestParameters: FindSdohRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminDiarySdohResponse>> {
        if (requestParameters['diaryId'] == null) {
            throw new runtime.RequiredError(
                'diaryId',
                'Required parameter "diaryId" was null or undefined when calling findSdoh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/diaries/{diaryId}/sdoh`;
        urlPath = urlPath.replace(`{${"diaryId"}}`, encodeURIComponent(String(requestParameters['diaryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminDiarySdohResponseFromJSON(jsonValue));
    }

    /**
     * 특정 일기의 사회적 건강 결정요인(Social Determinants of Health) 정보를 조회합니다.
     * 일기 SDoH 조회
     */
    async findSdoh(requestParameters: FindSdohRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminDiarySdohResponse> {
        const response = await this.findSdohRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 일기와 연관된 복지로 서비스 정보를 조회합니다.
     * 일기 복지로 서비스 조회
     */
    async findWelfareServicesRaw(requestParameters: FindWelfareServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminDiaryWelfareServiceResponse>> {
        if (requestParameters['diaryId'] == null) {
            throw new runtime.RequiredError(
                'diaryId',
                'Required parameter "diaryId" was null or undefined when calling findWelfareServices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/diaries/{diaryId}/welfare-services`;
        urlPath = urlPath.replace(`{${"diaryId"}}`, encodeURIComponent(String(requestParameters['diaryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminDiaryWelfareServiceResponseFromJSON(jsonValue));
    }

    /**
     * 특정 일기와 연관된 복지로 서비스 정보를 조회합니다.
     * 일기 복지로 서비스 조회
     */
    async findWelfareServices(requestParameters: FindWelfareServicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminDiaryWelfareServiceResponse> {
        const response = await this.findWelfareServicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
