/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseDiaryCreateResponse,
  CommonResponseDiaryDatesResponse,
  CommonResponseDiaryDetailResponse,
  CommonResponseDiaryFindAllResponse,
  DiaryCreateRequest,
} from '../models/index';
import {
    CommonResponseDiaryCreateResponseFromJSON,
    CommonResponseDiaryCreateResponseToJSON,
    CommonResponseDiaryDatesResponseFromJSON,
    CommonResponseDiaryDatesResponseToJSON,
    CommonResponseDiaryDetailResponseFromJSON,
    CommonResponseDiaryDetailResponseToJSON,
    CommonResponseDiaryFindAllResponseFromJSON,
    CommonResponseDiaryFindAllResponseToJSON,
    DiaryCreateRequestFromJSON,
    DiaryCreateRequestToJSON,
} from '../models/index';

export interface CreateDiaryRequest {
    diaryCreateRequest: DiaryCreateRequest;
}

export interface FindAllDiariesByMeRequest {
    startDate?: Date;
    endDate?: Date;
}

export interface FindDatesRequest {
    month: string;
}

export interface FindDiaryByIdRequest {
    diaryId: string;
}

/**
 * 
 */
export class DiaryApi extends runtime.BaseAPI {

    /**
     * 새로운 일기를 작성합니다. 날짜, 내용, 감정, 질문 점수를 포함해야 합니다.
     * 일기 생성
     */
    async createDiaryRaw(requestParameters: CreateDiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseDiaryCreateResponse>> {
        if (requestParameters['diaryCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'diaryCreateRequest',
                'Required parameter "diaryCreateRequest" was null or undefined when calling createDiary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/diaries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiaryCreateRequestToJSON(requestParameters['diaryCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseDiaryCreateResponseFromJSON(jsonValue));
    }

    /**
     * 새로운 일기를 작성합니다. 날짜, 내용, 감정, 질문 점수를 포함해야 합니다.
     * 일기 생성
     */
    async createDiary(requestParameters: CreateDiaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseDiaryCreateResponse> {
        const response = await this.createDiaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 현재 사용자의 일기 목록을 조회합니다. 선택적으로 시작/종료 날짜로 필터링할 수 있습니다.
     * 내 일기 목록 조회
     */
    async findAllDiariesByMeRaw(requestParameters: FindAllDiariesByMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseDiaryFindAllResponse>> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/diaries/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseDiaryFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 현재 사용자의 일기 목록을 조회합니다. 선택적으로 시작/종료 날짜로 필터링할 수 있습니다.
     * 내 일기 목록 조회
     */
    async findAllDiariesByMe(requestParameters: FindAllDiariesByMeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseDiaryFindAllResponse> {
        const response = await this.findAllDiariesByMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 월에 일기가 작성된 날짜 목록을 조회합니다.
     * 월별 일기 작성 날짜 조회
     */
    async findDatesRaw(requestParameters: FindDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseDiaryDatesResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling findDates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/diaries/dates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseDiaryDatesResponseFromJSON(jsonValue));
    }

    /**
     * 특정 월에 일기가 작성된 날짜 목록을 조회합니다.
     * 월별 일기 작성 날짜 조회
     */
    async findDates(requestParameters: FindDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseDiaryDatesResponse> {
        const response = await this.findDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 일기의 상세 정보를 조회합니다.
     * 일기 상세 조회
     */
    async findDiaryByIdRaw(requestParameters: FindDiaryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseDiaryDetailResponse>> {
        if (requestParameters['diaryId'] == null) {
            throw new runtime.RequiredError(
                'diaryId',
                'Required parameter "diaryId" was null or undefined when calling findDiaryById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/diaries/{diaryId}`;
        urlPath = urlPath.replace(`{${"diaryId"}}`, encodeURIComponent(String(requestParameters['diaryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseDiaryDetailResponseFromJSON(jsonValue));
    }

    /**
     * 특정 일기의 상세 정보를 조회합니다.
     * 일기 상세 조회
     */
    async findDiaryById(requestParameters: FindDiaryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseDiaryDetailResponse> {
        const response = await this.findDiaryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
